version: '3'
services:
  dev-server:
    image: node:alpine
    container_name: nginx-reactjs-express-fe # You can set a custom container name
    working_dir: /app
    volumes:
      - .:/app # Mount your project directory into the container
    command: npm install vite && npm install create-vite && npm install # Start the Vite development server
    networks:
      - my-network

  web-server:
    image: nginx:1.25.2-alpine-slim
    container_name: nginx-reactjs-express-fe-nginx # You can set a custom container name
    ports:
      - "80:80" # Map port 80 in the container to the host
    volumes:
      - ./app/dist:/usr/share/nginx/html # Mount the built app into Nginx
    networks:
      - my-network

networks:
  my-network:
