version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
